name = "syvita-mining"
type = "webpack"

account_id = "1b716765706e783e5a7c99ad054a97ea"
workers_dev = true
route = "syvitamining/api/*"
zone_id = "bd9317240018ea784963a8d1784f841a"
compatibility_date = "2021-12-04"
webpack_config = "webpack.config.js"

kv_namespaces = [ 
  { binding = "CITYCOINS", id = "5bfb26a405404ff9b11bbeb9c2525226", preview_id = "623bba3e6d8b47f18cd070221afb877e" }
]

[triggers]
crons = ["*/1 * * * *"]